---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-system
  namespace: actions-runner-system
spec:
  chart:
    spec:
      chart: actions-runner-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
      version: 0.21.0
  values:
    authSecret:
      name: controller-manager
      create: false
    nodeSelector:
      kubernetes.io/os: linux
      kubernetes.io/arch: amd64
  interval: 1m0s